### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rohansx** [COST-SD/support#24]
### Name

Rohan 

### Linkedin url (if applicable)

#rsx0352

### Additional Context

This community is very giving and very supportive and would love to be part of it. Also, I want to contribute to the open source and since I am new here, I might need help. So, therefore I want to be part of this organization.

**Comment by getlost01** [comment]
Thank you for being so interested, you have received the invite link in your email. Join through it.
