### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Hasheditz** [COST-SD/support#5]
### Name

Harendra singh

### Linkedin url (if applicable)

https://www.linkedin.com/in/12-harendra-singh/

### Additional Context

 I am a new software developer with a passion for coding and a strong understanding of web development technologies, including HTML, CSS, and JavaScript and I want to join this open-source community to improve my skills

**Comment by getlost01** [comment]
Welcome, [hasheditz](https://github.com/hasheditz) ! let's join our community and have fun, we have sent you the invitation.
